services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - commute-analyzer-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      ORS_API_KEY: ${ORS_API_KEY}
      SRV_ADDR: :8080 
      SRV_ENV: prod

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        VITE_API_URL: /api/v1
    environment:
      BACKEND_URL: http://api:8080

volumes:
  commute-analyzer-data:
