services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ORS_API_KEY: ${ORS_API_KEY}
      SRV_ADDR: :8080 
      SRV_ENV: prod

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        VITE_API_URL: /api/v1
    environment:
      BACKEND_URL: http://api:8080
