// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commute.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCommute = `-- name: CreateCommute :one
INSERT INTO commutes (
    user_id, name, home_point, office_point, route_geometry,
    distance_km, duration_min, vehicle, fuel_price, days_per_week,
    annual_cost, annual_minutes
) VALUES (
    $1, $2, 
    ST_SetSRID(ST_GeomFromWKB($10::bytea), 4326), 
    ST_SetSRID(ST_GeomFromWKB($11::bytea), 4326), 
    ST_SetSRID(ST_GeomFromWKB($12::bytea), 4326), 
    $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, annual_cost, annual_minutes, created_at
`

type CreateCommuteParams struct {
	UserID        uuid.UUID
	Name          *string
	DistanceKm    float64
	DurationMin   float64
	Vehicle       string
	FuelPrice     int32
	DaysPerWeek   int16
	AnnualCost    int64
	AnnualMinutes int64
	HomePoint     []byte
	OfficePoint   []byte
	RouteGeometry []byte
}

type CreateCommuteRow struct {
	ID            uuid.UUID
	AnnualCost    int64
	AnnualMinutes int64
	CreatedAt     time.Time
}

func (q *Queries) CreateCommute(ctx context.Context, arg CreateCommuteParams) (CreateCommuteRow, error) {
	row := q.db.QueryRow(ctx, createCommute,
		arg.UserID,
		arg.Name,
		arg.DistanceKm,
		arg.DurationMin,
		arg.Vehicle,
		arg.FuelPrice,
		arg.DaysPerWeek,
		arg.AnnualCost,
		arg.AnnualMinutes,
		arg.HomePoint,
		arg.OfficePoint,
		arg.RouteGeometry,
	)
	var i CreateCommuteRow
	err := row.Scan(
		&i.ID,
		&i.AnnualCost,
		&i.AnnualMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCommute = `-- name: DeleteCommute :exec
DELETE FROM commutes WHERE id = $1
`

func (q *Queries) DeleteCommute(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommute, id)
	return err
}

const getCommute = `-- name: GetCommute :one
SELECT 
    id, user_id, name, 
    ST_AsBinary(home_point) AS home_point, 
    ST_AsBinary(office_point) AS office_point, 
    distance_km, duration_min, vehicle, fuel_price, days_per_week, 
    annual_cost, annual_minutes, created_at, updated_at,
    ST_AsBinary(route_geometry) AS route_geometry
FROM commutes WHERE id = $1
`

type GetCommuteRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          *string
	HomePoint     interface{}
	OfficePoint   interface{}
	DistanceKm    float64
	DurationMin   float64
	Vehicle       string
	FuelPrice     int32
	DaysPerWeek   int16
	AnnualCost    int64
	AnnualMinutes int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	RouteGeometry interface{}
}

func (q *Queries) GetCommute(ctx context.Context, id uuid.UUID) (GetCommuteRow, error) {
	row := q.db.QueryRow(ctx, getCommute, id)
	var i GetCommuteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.HomePoint,
		&i.OfficePoint,
		&i.DistanceKm,
		&i.DurationMin,
		&i.Vehicle,
		&i.FuelPrice,
		&i.DaysPerWeek,
		&i.AnnualCost,
		&i.AnnualMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteGeometry,
	)
	return i, err
}

const listCommutesByUser = `-- name: ListCommutesByUser :many
SELECT 
    id, user_id, name, 
    ST_AsBinary(home_point) AS home_point, 
    ST_AsBinary(office_point) AS office_point, 
    distance_km, duration_min, vehicle, fuel_price, days_per_week, 
    annual_cost, annual_minutes, created_at, updated_at,
    ST_AsBinary(route_geometry) AS route_geometry
FROM commutes WHERE user_id = $1 ORDER BY created_at DESC
`

type ListCommutesByUserRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          *string
	HomePoint     interface{}
	OfficePoint   interface{}
	DistanceKm    float64
	DurationMin   float64
	Vehicle       string
	FuelPrice     int32
	DaysPerWeek   int16
	AnnualCost    int64
	AnnualMinutes int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	RouteGeometry interface{}
}

func (q *Queries) ListCommutesByUser(ctx context.Context, userID uuid.UUID) ([]ListCommutesByUserRow, error) {
	rows, err := q.db.Query(ctx, listCommutesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommutesByUserRow{}
	for rows.Next() {
		var i ListCommutesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.HomePoint,
			&i.OfficePoint,
			&i.DistanceKm,
			&i.DurationMin,
			&i.Vehicle,
			&i.FuelPrice,
			&i.DaysPerWeek,
			&i.AnnualCost,
			&i.AnnualMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RouteGeometry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommute = `-- name: UpdateCommute :one
UPDATE commutes SET
    name = COALESCE($2, name),
    vehicle = COALESCE($3, vehicle),
    fuel_price = COALESCE($4, fuel_price),
    days_per_week = COALESCE($5, days_per_week),
    home_point = CASE
        WHEN $6::bytea IS NOT NULL
        THEN ST_SetSRID(ST_GeomFromWKB($6::bytea), 4326)
        ELSE home_point
    END,
    office_point = CASE
        WHEN $7::bytea IS NOT NULL
        THEN ST_SetSRID(ST_GeomFromWKB($7::bytea), 4326)
        ELSE office_point
    END,
    route_geometry = CASE
        WHEN $8::bytea IS NOT NULL
        THEN ST_SetSRID(ST_GeomFromWKB($8::bytea), 4326)
        ELSE route_geometry
    END,
    distance_km = COALESCE($9, distance_km),
    duration_min = COALESCE($10, duration_min),
    annual_cost = COALESCE($11, annual_cost),
    annual_minutes = COALESCE($12, annual_minutes),
    updated_at = NOW()
WHERE id = $1
RETURNING id, annual_cost, annual_minutes, created_at
`

type UpdateCommuteParams struct {
	ID            uuid.UUID
	Name          *string
	Vehicle       *string
	FuelPrice     *int32
	DaysPerWeek   *int16
	HomePoint     []byte
	OfficePoint   []byte
	RouteGeometry []byte
	DistanceKm    *float64
	DurationMin   *float64
	AnnualCost    *int64
	AnnualMinutes *int64
}

type UpdateCommuteRow struct {
	ID            uuid.UUID
	AnnualCost    int64
	AnnualMinutes int64
	CreatedAt     time.Time
}

func (q *Queries) UpdateCommute(ctx context.Context, arg UpdateCommuteParams) (UpdateCommuteRow, error) {
	row := q.db.QueryRow(ctx, updateCommute,
		arg.ID,
		arg.Name,
		arg.Vehicle,
		arg.FuelPrice,
		arg.DaysPerWeek,
		arg.HomePoint,
		arg.OfficePoint,
		arg.RouteGeometry,
		arg.DistanceKm,
		arg.DurationMin,
		arg.AnnualCost,
		arg.AnnualMinutes,
	)
	var i UpdateCommuteRow
	err := row.Scan(
		&i.ID,
		&i.AnnualCost,
		&i.AnnualMinutes,
		&i.CreatedAt,
	)
	return i, err
}
