// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Commute struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          *string
	HomePoint     interface{}
	OfficePoint   interface{}
	RouteGeometry interface{}
	DistanceKm    float64
	DurationMin   float64
	Vehicle       string
	FuelPrice     int32
	DaysPerWeek   int16
	AnnualCost    int64
	AnnualMinutes int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	UserID    uuid.UUID
	DeviceID  string
	CreatedAt time.Time
}
