// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCommute(ctx context.Context, arg CreateCommuteParams) (CreateCommuteRow, error)
	CreateUser(ctx context.Context, deviceID string) (uuid.UUID, error)
	DeleteCommute(ctx context.Context, id uuid.UUID) error
	GetCommute(ctx context.Context, id uuid.UUID) (Commute, error)
	GetUserByDeviceId(ctx context.Context, deviceID string) (uuid.UUID, error)
	ListCommutesByUser(ctx context.Context, userID uuid.UUID) ([]Commute, error)
	UpdateCommute(ctx context.Context, arg UpdateCommuteParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
