// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (device_id)
VALUES ($1)
RETURNING user_id
`

func (q *Queries) CreateUser(ctx context.Context, deviceID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, deviceID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByDeviceId = `-- name: GetUserByDeviceId :one
SELECT user_id FROM users WHERE device_id = $1 LIMIT 1
`

func (q *Queries) GetUserByDeviceId(ctx context.Context, deviceID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByDeviceId, deviceID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
